services:

  mysql_rent:
    image: mysql:8.0
    container_name: mysql_rent
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: rent_db
      MYSQL_USER: rent_user
      MYSQL_PASSWORD: rent_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_rent_data:/var/lib/mysql
    networks:
      - microservices_network

  mysql_customer:
    image: mysql:8.0
    container_name: mysql_customer
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: customer_db
      MYSQL_USER: customer_user
      MYSQL_PASSWORD: customer_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3308:3306"
    volumes:
      - mysql_customer_data:/var/lib/mysql
    networks:
      - microservices_network

  mysql_bike:
    image: mysql:8.0
    container_name: mysql_bike
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bike_db
      MYSQL_USER: bike_user
      MYSQL_PASSWORD: bike_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3309:3306"
    volumes:
      - mysql_bike_data:/var/lib/mysql
    networks:
      - microservices_network

  postgres_auth:
    image: postgres:16
    container_name: postgres_auth
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - microservices_network

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - microservices_network

volumes:
  mysql_rent_data:
  mysql_customer_data:
  mysql_bike_data:
  postgres_auth_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  microservices_network:
    driver: bridge