@baseUrl = http://localhost:7778

### 1. Registrar un nuevo usuario (Prueba esto primero)
POST {{baseUrl}}/register
Content-Type: application/json

{
  "name": "Vicente",
  "email": "vicente@mail.com",
  "password": "abcd.1234"
}

###

### 2. Iniciar sesión (Login) para obtener el Token JWT
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "vicente@mail.com",
  "password": "abcd.1234"
}