spring.application.name=cliente
server.port=4002

spring.datasource.url=jdbc:mysql://localhost:3308/cliente_db
spring.datasource.username=cliente_user
spring.datasource.password=cliente_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration