spring.application.name=moto
server.port=4003

spring.datasource.url=jdbc:mysql://localhost:3309/moto_db
spring.datasource.username=moto_user
spring.datasource.password=moto_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration